#!/usr/bin/env python3
from __future__ import annotations

import json
import sys
from pathlib import Path

if len(sys.argv) != 3:
    raise SystemExit(
        "Usage: generate_category_groups.py CONFIG_JSON OUTPUT_TS"
    )

config_path = Path(sys.argv[1])
output_path = Path(sys.argv[2])

data = json.loads(config_path.read_text(encoding="utf-8"))
settings = data.get("settings", {})
groups = data.get("groups", [])

if not isinstance(groups, list) or not groups:
    raise SystemExit("category-groups.json must contain a non-empty 'groups' array")

seen_group_names: set[str] = set()
seen_categories: dict[str, str] = {}

for group in groups:
    if not isinstance(group, dict):
        raise SystemExit("Every group must be an object")

    name = str(group.get("name", "")).strip()
    if not name:
        raise SystemExit("Every group requires a non-empty 'name'")

    key = name.casefold()
    if key in seen_group_names:
        raise SystemExit(f"Duplicate top-level group name: {name}")
    seen_group_names.add(key)

    categories = group.get("categories", [])
    if not isinstance(categories, list):
        raise SystemExit(f"Group {name!r}: 'categories' must be an array")

    cleaned = []
    for raw in categories:
        category = str(raw).strip()
        if not category:
            continue

        category_key = category.casefold()
        previous = seen_categories.get(category_key)
        if previous:
            raise SystemExit(
                f"Category {category!r} is mapped twice: {previous!r} and {name!r}"
            )

        seen_categories[category_key] = name
        cleaned.append(category)

    group["name"] = name
    group["icon"] = str(group.get("icon", "default")).strip() or "default"
    group["categories"] = cleaned

default_open = settings.get("default_open", [])
if not isinstance(default_open, list):
    raise SystemExit("settings.default_open must be an array")

clean = {
    "settings": {
        "default_open": [str(value).strip() for value in default_open if str(value).strip()],
        "remember_open_state": bool(settings.get("remember_open_state", True)),
        "show_uncategorised": bool(settings.get("show_uncategorised", True)),
        "show_group_channel_counts": bool(settings.get("show_group_channel_counts", True)),
        "single_open": bool(settings.get("single_open", True))
    },
    "groups": groups
}

ts = """// AUTO-GENERATED by scripts/generate_category_groups.py
// Edit config/category-groups.json, not this file.

export interface LiveTvTopCategoryGroup {
    name: string;
    icon: string;
    categories: string[];
}

export interface LiveTvCategoryGroupConfig {
    settings: {
        default_open: string[];
        remember_open_state: boolean;
        show_uncategorised: boolean;
        show_group_channel_counts: boolean;
        single_open: boolean;
    };
    groups: LiveTvTopCategoryGroup[];
}

const liveTvCategoryGroupConfig: LiveTvCategoryGroupConfig = %s;

export default liveTvCategoryGroupConfig;
""" % json.dumps(clean, ensure_ascii=False, indent=4)

output_path.parent.mkdir(parents=True, exist_ok=True)
output_path.write_text(ts + "\n", encoding="utf-8")

print(f"Generated {output_path}")
for group in groups:
    print(f"  {group['name']}: {len(group['categories'])} mapped categories")
